#
# This file is automatically generated by the Terraform inventory module
#
---
all:
  vars:
    # Ansible
    ansible_connection: ssh
    ansible_user: ${ vm_user }
    ansible_ssh_private_key_file: ${ vm_ssh_private_key_file }
    ansible_become: yes

    # PTP
    ptp_enabled: ${ ptp_enabled }

    # vMotion Notifications
    vmotion_notifications_enabled: ${ vmotion_notifications_enabled }

crdb:
  hosts:
%{ for vm in crdb_vms ~}
    ${ vm.clone[0].customize[0].network_interface[0].ipv4_address }:
      hostname: ${ vm.name }
      fqdn: ${ vm.clone[0].customize[0].linux_options[0].host_name }.${ vm.clone[0].customize[0].linux_options[0].domain }
      uuid: ${ vm.id }
      ip: ${ vm.clone[0].customize[0].network_interface[0].ipv4_address }
%{ endfor ~}